version: '3.8'

services:
  bot:
    build: .
    container_name: sender-sms-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMINS=${ADMINS}
    env_file:
      - .env
    restart: unless-stopped
